<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIeNVYkx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIeNVYkx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIeNVYkx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIeNVYkx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIeNVYkx\App_KernelDevDebugContainer([
    'container.build_hash' => 'IeNVYkx',
    'container.build_id' => '73b4ee5e',
    'container.build_time' => 1748077604,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIeNVYkx');
